### ISSUE TITLE
can't find variable idb

### ISSUE THREAD

**Issue by solsticedhiver** [jakearchibald/safari-14-idb-fix#12]
So I rewrote my code to work around the mess that safari is doing at not caching audio sounds. So I am caching manually audio binary with indexDB and idb.

My code works fine on other browsers, and the last browser I test is safari where it fails with an error:

    ReferenceError: Can't find variable idb

So this fix is really needed for safari 14? because I am testing in safari 15.

**Comment by jakearchibald** [comment]
Your question seems unrelated to this repo. Maybe it's related to https://github.com/jakearchibald/idb? Please provide a reduced demo of the issue you're seeing, else it's difficult to tell what's going on & what it relates to.
