### ISSUE TITLE
Crashes on older Safari

### ISSUE THREAD

**Issue by bhollis** [jakearchibald/safari-14-idb-fix#3]
Got a report on Safari 12.5.4:
![image (7)](https://user-images.githubusercontent.com/313208/122807531-8ee5be00-d280-11eb-9727-be0db71a9e2b.png)

**Comment by bhollis** [comment]
Probably fixed in https://github.com/jakearchibald/safari-14-idb-fix/commit/746f17ad50bacd1b689a6d444f3756a8420d01cb#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80

**Comment by jakearchibald** [comment]
Yep. Already fixed and published
